# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'docker-swarm'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
- job_name: 'prometheus'

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
  - targets: ['localhost:9090']

- job_name: 'grafana'
  # 设定DNS A记录
  dns_sd_configs:
    - names:
        - 'tasks.grafana'
      type: 'A'
      port: 3000
  # 把__meta_dns_name的值设置到指标的 grafana 这个label里
  relabel_configs:
    - source_labels: ['__meta_dns_name']
      target_label: 'grafana'

- job_name: 'cadvisor'
  # 设定DNS A记录
  dns_sd_configs:
  - names:
    - 'tasks.cadvisor'
    type: 'A'
    port: 8080
  # 把__meta_dns_name的值设置到指标的 cadvisor 这个label里
  relabel_configs:
  - source_labels: ['__meta_dns_name']
    target_label: 'cadvisor'

- job_name: 'node-exporter'
  # 设定DNS A记录
  dns_sd_configs:
  - names:
    - 'tasks.node-exporter'
    type: 'A'
    port: 9100
  # 把__meta_dns_name的值设置到指标的 node-exporter 这个label里
  relabel_configs:
  - source_labels: ['__meta_dns_name']
    target_label: 'node_exporter'